workflows:
  ios-no-sign:
    name: Build iOS unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
